version: 1.0.{build}
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
environment:
  DeployExtension: false
before_build:
  - nuget restore
build:
  verbosity: minimal
artifacts:
- path: XTplus.Templates.Extension\bin\Debug\XTplus.Templates.Extension.2019.vsix
  name: XTplus.Templates.Extension.vsix